version: "3.9"

services:
  app:
    build:
      context: ./speedygo-user-service
      dockerfile: Dockerfile
    container_name: speedygo-user-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/speedygo_user?serverVersion=15&charset=utf8"
      KEYCLOAK_ISSUER: "http://localhost:8080/realms/SpeedyGo"
      KEYCLOAK_JWKS_URL: "http://host.docker.internal:8080/realms/SpeedyGo/protocol/openid-connect/certs"
    volumes:
      - ./speedygo-user-service:/var/www/html
    depends_on:
      - db
    networks:
      - speedygo

  web:
    image: nginx:stable
    container_name: speedygo-user-web
    ports:
      - "8084:80"
    volumes:
      - ./speedygo-user-service:/var/www/html
      - ./speedygo-user-service/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - speedygo

  db:
    image: postgres:15
    container_name: speedygo-user-db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: speedygo_user
    ports:
      - "5436:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    networks:
      - speedygo

volumes:
  pgdata_user:

networks:
  speedygo:
