# config/routes/cors.yaml
options_cors:
  path: /{any}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: ''
  requirements:
    any: ".+"
  methods: [OPTIONS]
