security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/
      stateless: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\KeycloakGuardAuthenticator

  access_control:
    # public
    - { path: ^/auth/register, roles: PUBLIC_ACCESS }
    - { path: ^/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/auth/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/auth/logout, roles: PUBLIC_ACCESS }

    # protected
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api/driver, roles: ROLE_DRIVER }
    - { path: ^/api, roles: ROLE_USER }

  role_hierarchy:
    ROLE_ADMIN: [ROLE_DRIVER, ROLE_USER]
    ROLE_DRIVER: [ROLE_USER]
